---
- name: check /etc/systemd/resolved.conf.d/resolved.conf exists
  stat:
    path: "/etc/systemd/resolved.conf.d/resolved.conf"
  register: __resolved_is_exist
  become: true
  tags: resolved

- name: check dnsstubliner is set to no
  command: "grep -q \"DNSStubListener=no\" /etc/systemd/resolved.conf.d/resolved.conf"
  args:
    warn: false
  changed_when: false
  register: __resolved
  when: __resolved_is_exist.stat.exists
  become: true
  tags: adguard_exporter

- name: create conf.d directory
  file:
    path: "/etc/systemd/resolved.conf.d"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  when: not __resolved_is_exist.stat.exists
  become: true
  tags: resolved

- name: configure /etc/systemd/resolved.conf.d/resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-resolved
  become: true
  tags: resolved

- name: remvove old resolv.conf
  file:
    path: "/etc/resolv.conf"
    state: absent
  when: not __resolved_is_exist.stat.exists
  become: true
  tags: resolved

- name: link resolv.conf to /run/systemd/resolve/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
  when: not __resolved_is_exist.stat.exists
  notify: restart systemd-resolved
  become: true
  tags: resolved